version: '3.1'

services:
  epa-db:
    image: postgres:16-alpine
    container_name: epa-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=epa-backend
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root