server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    url: jdbc:postgresql:epa-backend
    username: postgres

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
      dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

logging:
  level:
    org:
      springframework:
        orm:
          jpa: info
          JpaTransactionManager: debug
        transaction: info
    spring security: info
    web: info