spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}
      password: ${SPRING_REDIS_PASSWORD}

logging:
  level:
    org:
      springframework:
        orm:
          jpa: info
          JpaTransactionManager: debug
        transaction: info
    spring security: info
    web: info

token:
  secret:
    access: ${TOKEN_SECRET_ACCESS}
    refresh: ${TOKEN_SECRET_REFRESH}
  duration:
    access: ${TOKEN_DURATION_ACCESS}
    refresh: ${TOKEN_DURATION_REFRESH}
admin:
  login: admin
  password: admin