spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/epa-backend
    username: postgres
    password: root
  liquibase:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        ddl-auto: none
        show-sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}

logging:
  level:
    org:
      zalando:
        logbook: TRACE
      springframework:
        orm:
          jpa: info
          JpaTransactionManager: debug
        transaction: info
        web:
          servlet:
            DispatcherServlet: debug
    spring security: info
    web: info

token:
  secret:
    access: 51Ph61VOzrdwNvRa9FZclUpZRU160G1O
    refresh: 8D9EBD851C91433192222F47B89A4
  duration:
    access: 10m
    refresh: 15d
admin:
  login: admin
  password: admin
percentage_of_tasks_completed_on_time : 80
percentage_of_tasks_delayed : 60