DROP TABLE IF EXISTS projects, employees, tasks, employees_tasks, projects_tasks, projects_employees, criteria,
    questionnaires, questionnaires_criterias, employee_evaluation, recommendations CASCADE;

CREATE TABLE IF NOT EXISTS projects
(
    id               BIGINT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    status           VARCHAR(100) NOT NULL,
    created          DATE
);

CREATE TABLE IF NOT EXISTS employees
(
    id               BIGINT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(255) NOT NULL,
    nick_name        VARCHAR(32),
    city             VARCHAR(255),
    email            VARCHAR(50)  NOT NULL  UNIQUE,
    password         VARCHAR      NOT NULL,
    birthday         DATE,
    role             VARCHAR(100),
    position         VARCHAR(255),
    department       VARCHAR(100),
    creator_id       BIGINT                 REFERENCES employees (id),
    created          DATE
);

CREATE TABLE IF NOT EXISTS tasks
(
    id               BIGINT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    description      VARCHAR(255) NOT NULL,
    project_id       BIGINT       NOT NULL  REFERENCES projects (id),
    executor_id      BIGINT                 REFERENCES employees (id),
    create_date      DATE,
    start_date       DATE,
    dead_line        DATE,
    finish_date      DATE,
    status           VARCHAR(255),
    basic_points     INTEGER      NOT NULL,
    points           INTEGER,
    penalty_points   INTEGER      NOT NULL,
    owner_id         BIGINT       NOT NULL  REFERENCES employees (id)
);

CREATE TABLE IF NOT EXISTS employees_tasks
(
    employee_id      BIGINT       NOT NULL  REFERENCES employees (id),
    task_id          BIGINT       NOT NULL  REFERENCES tasks (id),
    PRIMARY KEY (employee_id, task_id)
);

CREATE TABLE IF NOT EXISTS projects_employees
(
    project_id       BIGINT       NOT NULL  REFERENCES projects (id),
    employee_id      BIGINT       NOT NULL  REFERENCES employees (id),
    PRIMARY KEY (project_id, employee_id)
);

CREATE TABLE IF NOT EXISTS criteria
(
    id               BIGINT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL  UNIQUE,
    is_default       BOOLEAN                DEFAULT FALSE
);

CREATE TABLE IF NOT EXISTS questionnaires
(
    id               BIGINT                 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author_id        BIGINT                 REFERENCES employees (id),
    created          DATE,
    status           VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS questionnaires_criterias
(
    questionnaire_id BIGINT                 REFERENCES questionnaires (id),
    criteria_id      BIGINT                 REFERENCES criteria (id),
    PRIMARY KEY (questionnaire_id, criteria_id)
);

CREATE TABLE IF NOT EXISTS employee_evaluation
(
    id               BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    evaluated_id     BIGINT                  REFERENCES employees (id),
    evaluator_id     BIGINT                  REFERENCES employees (id),
    questionnaire_id BIGINT                  REFERENCES questionnaires (id),
    create_day       DATE,
    criteria_id      BIGINT                  REFERENCES criteria (id),
    score            INTEGER,
    CONSTRAINT uq_employee_evaluation_for_evaluated_id_evaluator_id_criteria_id_questionnaire_id
               UNIQUE (evaluated_id, evaluator_id, criteria_id, questionnaire_id)
);

CREATE TABLE IF NOT EXISTS recommendations
(
    id               BIGINT                  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_id     BIGINT                  REFERENCES employees (id),
    sender_id        BIGINT                  REFERENCES employees (id),
    questionnaire_id BIGINT                  REFERENCES questionnaires (id),
    create_day       DATE,
    recommendation   VARCHAR       NOT NULL,
    CONSTRAINT uq_recommendation_for_recipient_id_sender_id_create_day
               UNIQUE (recipient_id, sender_id, questionnaire_id)
);